// <auto-generated />
using API.Response.Dynamic.Model.Infrastructures.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Response.Dynamic.Model.DataMigration.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240515131512_ApiDemandSqlCode_Table")]
    partial class ApiDemandSqlCode_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Response.Dynamic.Model.Domain.Models.ApiDemandProperties", b =>
                {
                    b.Property<string>("ID_Properties")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApiDemandPropertiesID_Properties")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApiDemandRequestID_Demand")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Fk_ID_Demand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Properties");

                    b.HasIndex("ApiDemandPropertiesID_Properties");

                    b.HasIndex("ApiDemandRequestID_Demand");

                    b.ToTable("ApiDemandProperties", (string)null);
                });

            modelBuilder.Entity("API.Response.Dynamic.Model.Domain.Models.ApiDemandRequest", b =>
                {
                    b.Property<string>("ID_Demand")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BDDType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataModelNumberProperties")
                        .HasColumnType("int");

                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.HasKey("ID_Demand");

                    b.ToTable("ApiDemandRequest", (string)null);
                });

            modelBuilder.Entity("API.Response.Dynamic.Model.Domain.Models.ApiDemandSqlCode", b =>
                {
                    b.Property<string>("ID_SqlCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Fk_ID_Demand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<string>("SqlCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SqlWhereClause")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_SqlCode");

                    b.ToTable("ApiDemandSqlCode", (string)null);
                });

            modelBuilder.Entity("API.Response.Dynamic.Model.Domain.Models.ApiDemandProperties", b =>
                {
                    b.HasOne("API.Response.Dynamic.Model.Domain.Models.ApiDemandProperties", null)
                        .WithMany()
                        .HasForeignKey("ApiDemandPropertiesID_Properties");

                    b.HasOne("API.Response.Dynamic.Model.Domain.Models.ApiDemandRequest", null)
                        .WithMany()
                        .HasForeignKey("ApiDemandRequestID_Demand");
                });
#pragma warning restore 612, 618
        }
    }
}
